name: Develop CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: "17"
          cache: 'gradle'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true


      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Run Integration Tests
        run: flutter test # --tags integration

      - name: Build APK and AAB
        run: |
          flutter build apk --release
          flutter build appbundle

      - name: Compress Android Archives
        run: |
          cd build
          tar -czf android_builds.tar.gz app/outputs/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android_builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
            build/android_builds.tar.gz
